### ISSUE TITLE
Impossible to install this package

### ISSUE THREAD

**Issue by Farris27** [lachezargrigorov/laravel-shopping-cart#1]
Hello i'm sorry but for the moment. 

the composer install not function :s 

$ composer require lachezargrigorov\laravel-shopping-cart

                                                                                                                                                                         
  [InvalidArgumentException]                                                                                                                                             
  Could not find package lachezargrigorovlaravel-shopping-cart at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  

or $ composer require lachezargrigorov\laravel-shopping-cart:1.0.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lachezargrigorovlaravel-shopping-cart could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by lachezargrigorov** [comment]
Hi,
use / instead of \ 

$ composer require lachezargrigorov/laravel-shopping-cart

**Comment by Farris27** [comment]
Thanks ;)
