### ISSUE TITLE
proposition 

### ISSUE THREAD

**Issue by Farris27** [lachezargrigorov/laravel-shopping-cart#2]
Proposition for this project :) 

add : 
class Product extends Model implements Item{
    public function getCartPrice()
{
    return $this->price;
}
}

for the total :)

**Comment by lachezargrigorov** [comment]
What do you mean?

**Comment by Farris27** [comment]
when i implement this package in my model ... The price total and subtotal i have problem

but if i add this->price; 

it's word perfectly :)

**Comment by lachezargrigorov** [comment]
As the readme say you must implement the Item interface in your Product class

 "Implement the Item Interface in your item (product) model."

The implementation of the getCartPrice method depends from the price column of the product model. 

For example: 

`public function getCartPrice()
    {
        $price = $this->getPrice();

        if(is_array($price))
        {
            return $price["discount_price"];
        }

        return $price;
    }`
