### ISSUE TITLE
Special ItemCondition for x + 1 free 

### ISSUE THREAD

**Issue by Farris27** [lachezargrigorov/laravel-shopping-cart#3]
Hello it's possible to make condition for special offers : 

x+1 free ? 

 public function addLivres($id)
    {
        $livre= Livres::find($id);

        $quantite=Cart::item($id)->quantity;

        if($livre->promos)
        {
            $condition = intval($livre->promos->condition1);
            dd($condition, $quantite);
            if($quantite <= $condition ){Cart::item($id)->addQuantity(1)->model;
                Cart::item($id)->setConditionAsArray([
                    "name"  => "testPromo",

                    "value" => "-100%",
                ]);}else {

                Cart::item($id)->addQuantity(1)->model;
                Cart::item($id)->setConditionAsArray([
                    "name"  => "testPromo",

                    "value" => "-10%",
                ]);}

        }
        else{
            Cart::item($id)->addQuantity(1)->model;
        }
        flash('Produit ajoute au panier')->success();
        return back();
    }

**Comment by lachezargrigorov** [comment]
What do you mean ? And this is not a issue ! I'm going to close this ...

**Comment by lachezargrigorov** [comment]
There is already Condition for this. 

```php
if(Cart::item($id)->quantity == 2)
{
    Cart::item($id)->condition('one free')->value('-'.Cart::item($id)->price);
}
```
