### ISSUE TITLE
Question Two models? 

### ISSUE THREAD

**Issue by Farris27** [lachezargrigorov/laravel-shopping-cart#4]
Hi , i'm use this package for my project of development. thanks for this package. 
## Detailed description

When i use for only model , it's work but its is possible add other model as the same project ? 

How make the difference in my controller?if he is possible ? 

##  My environment

* Version used : PHP 7.1
* Operating system and version : MAC os x el capitan
* Link to your project: /

Thanks for all

**Comment by la40** [comment]
If I understand you correct. You just want to load different models. This is very unusual and not recommended. 

### Solution
Download the new v.1.1.1 release. I've implemented Cart::emptyModels that will do the job.

```php
Cart::item(x)->model->some_prop; //this will load the models for cart.item_class in settings
Cart::emptyModels();
config(['cart.item_class'=>'App\Product2']); 
Cart::item(x)->model->some_prop; //this will load the models again for cart.item_class in settings but that is now Product2
```
